# Generated by Django 5.1 on 2024-09-18 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='line_user_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
