# Generated by Django 5.1 on 2024-09-24 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_users_line_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='preferred_area',
        ),
    ]
