# Generated by Django 5.1 on 2024-10-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_users_username_alter_users_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='unique_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
