# Generated by Django 5.1 on 2025-02-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_users_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='line_user_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
