# Generated by Django 5.1 on 2024-09-17 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LineMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('reply_token', models.CharField(blank=True, max_length=100, null=True)),
                ('message_type', models.CharField(default='text', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sent_by_user', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
