# Generated by Django 5.1 on 2024-09-17 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linemessagingapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LineMessage',
        ),
    ]
