# Generated by Django 5.1 on 2024-09-18 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('linemessagingapi', '0002_delete_linemessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LineChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('channel_id', models.CharField(db_index=True, max_length=50)),
                ('channel_access_token', models.TextField()),
                ('channel_secret', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LineChannelContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.CharField(db_index=True, max_length=50)),
                ('display_name', models.CharField(blank=True, max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_channel_contacts', to='linemessagingapi.linechannel')),
            ],
        ),
        migrations.CreateModel(
            name='LineMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('reply_token', models.CharField(blank=True, max_length=100, null=True)),
                ('message_type', models.CharField(default='text', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sent_by_user', models.BooleanField(default=False)),
                ('webhook_data', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
