# Generated by Django 5.1 on 2024-09-21 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linemessagingapi', '0004_linechannel_bot_id_linechannelcontact_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linemessage',
            name='sent_by_user',
        ),
        migrations.RemoveField(
            model_name='linemessage',
            name='timestamp',
        ),
    ]
