# Generated by Django 5.1 on 2024-09-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linemessagingapi', '0005_remove_linemessage_sent_by_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=255)),
                ('headers', models.JSONField()),
                ('body', models.TextField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='LineMessage',
        ),
    ]
