# Generated by Django 5.1 on 2024-09-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linemessagingapi', '0006_webhookrequest_delete_linemessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linechannel',
            name='channel_access_token',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
