# Generated by Django 5.1 on 2024-09-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linemessagingapi', '0007_alter_linechannel_channel_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookrequest',
            name='response_status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
