# Generated by Django 5.1 on 2024-10-22 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linemessagingapi', '0010_lineusertokenmapping'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LineUserTokenMapping',
        ),
    ]
