# Generated by Django 5.1 on 2024-10-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linemessagingapi', '0012_noncemapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='noncemapping',
            name='line_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
