# Generated by Django 5.1 on 2024-10-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linemessagingapi', '0013_noncemapping_line_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='noncemapping',
            name='line_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='noncemapping',
            name='line_user_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
