# Generated by Django 5.1 on 2024-10-23 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linemessagingapi', '0015_alter_noncemapping_nonce_alter_noncemapping_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noncemapping',
            old_name='line_token',
            new_name='link_token',
        ),
    ]
