# Generated by Django 5.1 on 2025-02-17 07:43

import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linemessagingapi', '0017_remove_noncemapping_line_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noncemapping',
            name='user',
        ),
        migrations.AlterField(
            model_name='noncemapping',
            name='nonce',
            field=models.CharField(default=secrets.token_urlsafe, max_length=255, unique=True),
        ),
    ]
