# Generated by Django 5.1 on 2025-02-26 14:44

import linemessagingapi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linemessagingapi', '0018_remove_noncemapping_user_alter_noncemapping_nonce'),
    ]

    operations = [
        migrations.AddField(
            model_name='noncemapping',
            name='state',
            field=models.CharField(default=linemessagingapi.models.generate_state, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='noncemapping',
            name='nonce',
            field=models.CharField(default=linemessagingapi.models.generate_nonce, max_length=255, unique=True),
        ),
    ]
