# Generated by Django 5.1 on 2025-02-26 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linemessagingapi', '0019_noncemapping_state_alter_noncemapping_nonce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noncemapping',
            name='state',
        ),
    ]
