# Generated by Django 5.1 on 2025-02-26 19:41

import linemessagingapi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linemessagingapi', '0020_remove_noncemapping_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='noncemapping',
            name='state',
            field=models.CharField(default=linemessagingapi.models.generate_state, max_length=255, unique=True),
        ),
    ]
