# Generated by Django 5.1 on 2025-03-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linemessagingapi', '0021_noncemapping_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='noncemapping',
            name='redirect_path',
            field=models.CharField(blank=True, default='/callback', max_length=255),
        ),
    ]
