# Generated by Django 5.1 on 2025-03-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linemessagingapi', '0022_noncemapping_redirect_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linechannelcontact',
            name='display_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
