# Generated by Django 5.1 on 2025-05-16 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linemessagingapi', '0023_alter_linechannelcontact_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noncemapping',
            name='redirect_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
