# Generated by Django 5.1 on 2024-09-08 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationlocation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='donationlocation',
            name='longtitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=15, null=True),
        ),
    ]
