# Generated by Django 5.1 on 2024-09-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_donationlocation_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationlocation',
            name='keyword',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
