# Generated by Django 5.1 on 2024-09-10 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_donationlocation_googlemap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationlocation',
            old_name='sub_district',
            new_name='subdistrict',
        ),
    ]
