# Generated by Django 5.1 on 2024-09-10 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_rename_sub_district_donationlocation_subdistrict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.region'),
        ),
    ]
