# Generated by Django 5.1 on 2024-09-18 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_province_region'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district', to='webapp.province'),
        ),
        migrations.AlterField(
            model_name='donationhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donationlocation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='donationlocation',
            name='longtitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='donationlocation',
            name='subdistrict',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donation_location', to='webapp.subdistrict'),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='webapp.donationlocation'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='province',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='province', to='webapp.region'),
        ),
        migrations.AlterField(
            model_name='subdistrict',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdistrict', to='webapp.district'),
        ),
    ]
