# Generated by Django 5.1 on 2024-09-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_district_province_alter_donationhistory_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationlocation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='donationlocation',
            name='longtitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
    ]
