# Generated by Django 5.1 on 2024-09-18 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_donationlocation_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='webapp.province'),
        ),
        migrations.AlterField(
            model_name='donationhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donationlocation',
            name='subdistrict',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donation_locations', to='webapp.subdistrict'),
        ),
        migrations.AlterField(
            model_name='province',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='webapp.region'),
        ),
        migrations.AlterField(
            model_name='subdistrict',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdistricts', to='webapp.district'),
        ),
    ]
