# Generated by Django 5.1 on 2024-09-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_preferredarea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferredarea',
            name='district',
        ),
        migrations.RemoveField(
            model_name='preferredarea',
            name='province',
        ),
        migrations.RemoveField(
            model_name='preferredarea',
            name='subdistrict',
        ),
        migrations.AddField(
            model_name='preferredarea',
            name='districts',
            field=models.ManyToManyField(blank=True, related_name='preferred_areas', to='webapp.district'),
        ),
        migrations.AddField(
            model_name='preferredarea',
            name='provinces',
            field=models.ManyToManyField(blank=True, related_name='preferred_areas', to='webapp.province'),
        ),
        migrations.AddField(
            model_name='preferredarea',
            name='subdistricts',
            field=models.ManyToManyField(blank=True, related_name='preferred_areas', to='webapp.subdistrict'),
        ),
    ]
