# Generated by Django 5.1 on 2024-09-28 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_remove_preferredarea_district_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationlocation',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
