# Generated by Django 5.1 on 2024-09-28 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_announcements'),
        ('webapp', '0013_rename_longtitude_donationlocation_longitude'),
    ]

    operations = [
    ]
