# Generated by Django 5.1 on 2024-10-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_alter_donationlocation_facility_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
