# Generated by Django 5.1 on 2024-10-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_alter_donationlocation_facility_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='detail',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
