# Generated by Django 5.1 on 2024-10-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_alter_post_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationlocation',
            name='facility_type',
            field=models.CharField(blank=True, choices=[('1', 'โรงพยาบาล'), ('2', 'ศูนย์กาชาด'), ('3', 'หน่วยรับบริจาคเคลื่อนที่')], max_length=50, null=True),
        ),
    ]
