# Generated by Django 5.1 on 2024-10-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_alter_donationlocation_facility_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationlocation',
            name='facility_type',
            field=models.CharField(blank=True, choices=[('ร', 'โรงพยาบาล'), ('ศ', 'ศูนย์กาชาด'), ('ค', 'หน่วยรับบริจาคเคลื่อนที่')], max_length=50, null=True),
        ),
    ]
