# Generated by Django 5.1 on 2024-10-16 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_alter_donationlocation_facility_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationlocation',
            name='facility_type',
        ),
    ]
