# Generated by Django 5.1 on 2024-10-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_donationlocation_facility_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationlocation',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
