# Generated by Django 5.1 on 2024-12-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_alter_donationlocation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationhistory',
            name='donation_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
