# Generated by Django 5.1 on 2025-01-12 23:27

import webapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_donationhistory_donation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationhistory',
            name='donation_image',
            field=models.FileField(blank=True, null=True, storage=webapp.models.GCSMediaStorage(), upload_to=''),
        ),
    ]
