# Generated by Django 5.1 on 2025-01-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0028_remove_preferredarea_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='new_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
