# Generated by Django 5.1 on 2025-02-01 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0030_alter_post_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferredarea',
            name='districts',
        ),
        migrations.RemoveField(
            model_name='preferredarea',
            name='provinces',
        ),
        migrations.AddField(
            model_name='preferredarea',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferred_areas', to='webapp.district'),
        ),
        migrations.AddField(
            model_name='preferredarea',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferred_areas', to='webapp.province'),
        ),
    ]
