# Generated by Django 5.1 on 2025-02-01 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0031_remove_preferredarea_districts_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferredarea',
            name='province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='preferred_areas', to='webapp.province'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preferredarea',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='preferred_areas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
