# Generated by Django 5.1 on 2025-02-02 05:32

import webapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0032_alter_preferredarea_province_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationhistory',
            name='donation_point',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='donationhistory',
            name='donation_type',
            field=models.CharField(choices=[('ปกติ', 'บริจาคโลหิตทั่วไป'), ('ฉุกเฉิน', 'บริจาคโลหิตฉุกเฉิน')], default='ปกติ', max_length=10),
        ),
        migrations.AddField(
            model_name='donationhistory',
            name='donor_card_image',
            field=models.FileField(blank=True, null=True, storage=webapp.models.GCSMediaStorage(), upload_to=''),
        ),
        migrations.AddField(
            model_name='donationhistory',
            name='image_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donationhistory',
            name='share_status',
            field=models.BooleanField(default=False),
        ),
    ]
