# Generated by Django 5.1 on 2025-02-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0033_donationhistory_donation_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationhistory',
            name='donation_type',
            field=models.CharField(choices=[('ทั่วไป', 'บริจาคโลหิตทั่วไป'), ('ฉุกเฉิน', 'บริจาคโลหิตฉุกเฉิน')], default='ทั่วไป', max_length=10),
        ),
    ]
