# Generated by Django 5.1 on 2025-02-04 10:07

import webapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0034_alter_donationhistory_donation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.FileField(blank=True, null=True, storage=webapp.models.GCSMediaStorage(), upload_to=''),
        ),
    ]
