# Generated by Django 5.1 on 2025-02-04 14:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0035_announcement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='date updated'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='date updated'),
        ),
        migrations.AddField(
            model_name='event',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
        migrations.AddField(
            model_name='event',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='date updated'),
        ),
    ]
