# Generated by Django 5.1 on 2025-02-16 18:56

import webapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0037_alter_event_end_date_alter_event_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.FileField(blank=True, null=True, storage=webapp.models.GCSMediaStorage(), upload_to=webapp.models.announcement_image_upload_path),
        ),
        migrations.AlterField(
            model_name='donationhistory',
            name='donation_image',
            field=models.FileField(blank=True, null=True, storage=webapp.models.GCSMediaStorage(), upload_to=webapp.models.donation_image_upload_path),
        ),
        migrations.AlterField(
            model_name='donationhistory',
            name='donor_card_image',
            field=models.FileField(blank=True, null=True, storage=webapp.models.GCSMediaStorage(), upload_to=webapp.models.donor_card_upload_path),
        ),
    ]
