# Generated by Django 5.1 on 2025-02-17 10:27

import webapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0038_alter_announcement_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='image',
            field=models.FileField(blank=True, null=True, storage=webapp.models.GCSMediaStorage(), upload_to=webapp.models.achievement_image_upload_path),
        ),
    ]
