# Generated by Django 5.1 on 2025-02-17 10:59

import webapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0039_achievement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.FileField(blank=True, null=True, storage=webapp.models.GCSMediaStorage(), upload_to=webapp.models.event_image_upload_path),
        ),
    ]
