# Generated by Django 5.1 on 2025-02-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0041_donationhistory_number_like_alter_post_number_donor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationlocation',
            name='available_date',
        ),
        migrations.AddField(
            model_name='donationlocation',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donationlocation',
            name='started_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
