# Generated by Django 5.1 on 2025-02-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0042_remove_donationlocation_available_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationhistory',
            name='verify',
        ),
        migrations.AddField(
            model_name='donationhistory',
            name='verify_status',
            field=models.CharField(choices=[('pending', 'รอการตรวจสอบ'), ('verified', 'ได้รับการยืนยัน')], default='pending', max_length=10),
        ),
    ]
