# Generated by Django 5.1 on 2025-03-06 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0045_userpostinterest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationhistory',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.donationlocation'),
        ),
        migrations.AlterField(
            model_name='donationhistory',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_donation_histories', to='webapp.post'),
        ),
    ]
