# Generated by Django 5.1 on 2025-03-06 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0046_alter_donationhistory_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationhistory',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.donationlocation'),
        ),
    ]
